// Error envelope and codes (04-api.md §1). Messages are shown to users as-is.

export const ERROR_MESSAGES = {
  AUTH_REQUIRED: '로그인이 필요해요.',
  AUTH_INVALID_CREDENTIALS: '이메일 또는 비밀번호가 맞지 않아요.',
  AUTH_LOCKED: '로그인 시도가 너무 많아요. 잠시 후 다시 시도하세요.',
  AUTH_DISABLED: '비활성화된 계정이에요. 관리자에게 문의하세요.',
  AUTH_PASSWORD_CHANGE_REQUIRED: '비밀번호를 바꿔야 다른 화면을 쓸 수 있어요.',
  AUTH_PASSWORD_POLICY: '비밀번호 규칙에 맞지 않아요.',
  AUTH_CURRENT_PASSWORD_WRONG: '현재 비밀번호가 맞지 않아요.',
  CSRF_INVALID: '요청을 확인할 수 없어요. 새로고침 후 다시 시도하세요.',
  FORBIDDEN: '권한이 없어요.',
  VALIDATION_FAILED: '입력값을 확인해 주세요.',
  NAME_INVALID: '소문자·숫자·하이픈만, 3~30자, 하이픈으로 시작·끝 불가, -- 불가예요.',
  NAME_RESERVED: '예약된 이름이라 쓸 수 없어요.',
  NAME_TAKEN: '이미 쓰고 있는 이름이에요.',
  TEAM_NOT_FOUND: '팀을 찾을 수 없어요.',
  TEAM_NOT_RUNNING: '팀 에이전트가 꺼져 있어요.',
  NOT_FOUND: '찾을 수 없어요.',
  USER_NOT_FOUND: '사용자를 찾을 수 없어요.',
  USER_EMAIL_TAKEN: '이미 등록된 이메일이에요.',
  USER_EMPLOYEE_NO_TAKEN: '이미 쓰고 있는 사번이에요.',
  MEMBER_EXISTS: '이미 팀 멤버예요.',
  LAST_TEAM_ADMIN: '팀 관리자가 한 명은 있어야 해요.',
  TEAM_CONFIRM_MISMATCH: '팀 이름이 맞지 않아요.',
  DEPARTMENT_NOT_FOUND: '부서를 찾을 수 없어요.',
  DEPARTMENT_CODE_TAKEN: '이미 쓰고 있는 부서 코드예요.',
  DEPARTMENT_CYCLE: '자기 하위 부서 아래로는 옮길 수 없어요.',
  DEPARTMENT_TOO_DEEP: '부서는 10단계까지만 만들 수 있어요.',
  DEPARTMENT_NOT_EMPTY: '먼저 구성원과 하위 부서를 옮기세요.',
  DEPARTMENT_ARCHIVED: '보관된 부서에는 추가할 수 없어요.',
  IMPORT_INVALID_CSV: 'CSV 파일을 읽지 못했어요. 양식의 열 이름을 확인하세요.',
  IMPORT_STALE: '미리보기 이후 데이터가 바뀌었어요. 다시 미리보기 하세요.',
  IMPORT_HAS_ERRORS: '오류 행이 있어요. 오류 행을 빼고 적용하거나 파일을 고치세요.',
  TEMPLATE_NOT_FOUND: '에이전트 템플릿을 찾을 수 없어요.',
  TEMPLATE_IN_USE: '할당된 팀이 있어 삭제할 수 없어요. 먼저 할당을 해제하세요.',
  MODEL_NOT_ALLOWED: '허용되지 않은 모델이에요.',
  DRIVE_PATH_INVALID: '경로가 올바르지 않아요.',
  DRIVE_NOT_FOUND: '파일이나 폴더를 찾을 수 없어요.',
  DRIVE_EXISTS: '같은 이름이 이미 있어요.',
  DRIVE_QUOTA_EXCEEDED: '팀 드라이브 용량이 부족해요.',
  DRIVE_TOO_LARGE: '업로드하지 못했어요. 파일이 500MB를 넘어요.',
  APP_NOT_FOUND: '앱을 찾을 수 없어요.',
  APP_STATE_CONFLICT: '지금 상태에서는 할 수 없어요.',
  APP_NOT_PUBLIC: '공개된 앱이 아니에요.',
  APP_ALREADY_PUBLIC: '이미 공개된 앱이에요.',
  DEPLOY_ALREADY_PENDING: '이미 검토 중인 요청이 있어요.',
  MCP_NOT_FOUND: 'MCP를 찾을 수 없어요.',
  MCP_MANIFEST_INVALID: 'MCP 패키지를 확인해 주세요. 아래 문제를 고친 뒤 다시 올리세요.',
  MCP_TOO_LARGE: '업로드하지 못했어요. 패키지가 50MB를 넘어요.',
  MCP_VERSION_EXISTS: '이미 올린 버전이에요. platform-plugin.yaml과 package.json의 version을 올려 주세요.',
  MCP_ALREADY_INSTALLED: '이미 이 팀에 설치돼 있어요.',
  MCP_SUSPENDED: '게시가 중단된 MCP예요.',
  MCP_NOT_PUBLISHED: '아직 게시되지 않은 MCP예요.',
  MCP_PLATFORM_LOCKED: '플랫폼 기본 MCP는 제거할 수 없어요.',
  MCP_STATE_CONFLICT: '지금 상태에서는 할 수 없어요.',
  ORCHESTRATOR_UNAVAILABLE: '지금은 팀 에이전트를 켤 수 없어요. 잠시 후 다시 시도하세요.',
  INTERNAL: '문제가 생겼어요. 잠시 후 다시 시도하세요.',
} as const;

export type ErrorCode = keyof typeof ERROR_MESSAGES;

export interface ApiErrorBody {
  error: { code: ErrorCode | (string & {}); message: string; details?: Record<string, unknown> };
}
